export const TYPE_ACRONYMS: Record<string, [string, string, string, string]> = {
  INTJ: ["Introverted", "Intuitive", "Thinking", "Judging"],
  INTP: ["Introverted", "Intuitive", "Thinking", "Prospecting"],
  ENTJ: ["Extraverted", "Intuitive", "Thinking", "Judging"],
  ENTP: ["Extraverted", "Intuitive", "Thinking", "Prospecting"],
  INFJ: ["Introverted", "Intuitive", "Feeling", "Judging"],
  INFP: ["Introverted", "Intuitive", "Feeling", "Prospecting"],
  ENFJ: ["Extraverted", "Intuitive", "Feeling", "Judging"],
  ENFP: ["Extraverted", "Intuitive", "Feeling", "Prospecting"],
  ISTJ: ["Introverted", "Sensing", "Thinking", "Judging"],
  ISFJ: ["Introverted", "Sensing", "Feeling", "Judging"],
  ESTJ: ["Extraverted", "Sensing", "Thinking", "Judging"],
  ESFJ: ["Extraverted", "Sensing", "Feeling", "Judging"],
  ISTP: ["Introverted", "Sensing", "Thinking", "Prospecting"],
  ISFP: ["Introverted", "Sensing", "Feeling", "Prospecting"],
  ESTP: ["Extraverted", "Sensing", "Thinking", "Prospecting"],
  ESFP: ["Extraverted", "Sensing", "Feeling", "Prospecting"],
};

export type TypeProfile = {
  nickname: string;
  tagline: string;
  careers: string[];
  strengths: string[];
  blindSpots: string[];
  energyPattern: string;
  socialStyle: string;
  communicationTip: string;
  practiceScenarios: string[];
};

export const TYPE_PROFILES: Record<string, TypeProfile> = {
  INTJ: {
    nickname: "The Architect",
    tagline: "Strategic, independent, and relentlessly driven by long-term vision.",
    careers: ["Strategy consultant", "Software architect", "Research scientist", "Investment analyst", "Systems engineer", "Academic/professor"],
    strengths: ["Long-range strategic thinking", "Independent problem solving", "High standards and follow-through", "Cutting through inefficiency quickly", "Pattern recognition across complex systems"],
    blindSpots: ["Can come off as cold or dismissive", "Struggles with small talk — sees it as wasteful", "May overlook the emotional needs of others", "Perfectionism leads to overwork and delay", "Inflexible once committed to a plan"],
    energyPattern: "Recharges in solitude. Social events are draining unless deeply purposeful. Needs significant alone time after group interactions to feel recovered.",
    socialStyle: "Selective and intentional. Prefers 1-on-1 or small groups with substance. Quality over quantity. Will not sustain surface-level interactions for long.",
    communicationTip: "Lead with the why and the long-term logic. Skip pleasantries and get to substance quickly — they respect directness. Avoid vague or purely emotional appeals.",
    practiceScenarios: ["Networking at an industry conference", "Making small talk at a work social event", "Starting a conversation at a party where you know nobody", "One-on-one meeting with your manager", "Making small talk with the person next to you on a flight"],
  },
  INTP: {
    nickname: "The Thinker",
    tagline: "Analytical, curious, and constantly building mental models of how everything works.",
    careers: ["Software developer", "Data scientist", "Philosopher/academic", "Systems analyst", "Research scientist", "Technical writer"],
    strengths: ["Deep analytical and abstract thinking", "Seeing patterns others miss entirely", "Objective and detached problem solving", "Lateral thinking and original ideas", "Comfortable with ambiguity and complexity"],
    blindSpots: ["Analysis paralysis — thinks more than acts", "Can appear detached or uninterested in people", "Struggles with routine, structure, and admin", "Underestimates the value of emotion in decisions", "Procrastinates on execution and delivery"],
    energyPattern: "Highly introverted. Gets lost in thought naturally. Social energy is limited — prefers short, intellectually stimulating interactions over long casual ones.",
    socialStyle: "Awkward in small talk but fully engaged in intellectual discussion. Often misread as aloof or arrogant. Needs others to go beneath the surface to unlock them.",
    communicationTip: "Ask them about ideas, not feelings. Give them space to think before responding — they dislike being rushed. Theoretical and conceptual discussions engage them immediately.",
    practiceScenarios: ["Starting a conversation at a party where you know nobody", "Asking someone out on a first date", "Networking at an industry conference", "Joining a group conversation already in progress", "Reaching out to an old friend after a long gap"],
  },
  ENTJ: {
    nickname: "The Commander",
    tagline: "Natural leaders who think in systems and move people toward a goal.",
    careers: ["Executive/CEO", "Management consultant", "Lawyer", "Entrepreneur", "Project manager", "Military officer"],
    strengths: ["Natural leadership presence and authority", "Strategic decision-making under pressure", "Organizing people and resources efficiently", "Long-term vision with execution discipline", "Direct and confident communication"],
    blindSpots: ["Can be domineering or impatient", "May steamroll others' ideas without realizing it", "Blunt to the point of being genuinely harsh", "Struggles to slow down for emotional processing", "Over-optimizes for results at the cost of relationships"],
    energyPattern: "Energized by leading and executing. Aimless socializing drains them. Recharges through purposeful, productive work rather than passive rest.",
    socialStyle: "Takes charge in social settings automatically. Reads power dynamics immediately. Prefers conversations with purpose. Not naturally warm but deeply loyal once trust is built.",
    communicationTip: "Be direct, competent, and prepared. They lose respect for vagueness fast. Frame ideas in terms of outcomes and efficiency. Don't take their bluntness personally.",
    practiceScenarios: ["Listening without offering solutions — a friend needs to vent", "Having a difficult conversation without steamrolling", "Setting a boundary with someone without being harsh", "Recovering after saying something too blunt", "Being vulnerable with a friend about something personal"],
  },
  ENTP: {
    nickname: "The Debater",
    tagline: "Quick-thinking, idea-driven, and thrives on intellectual sparring and challenge.",
    careers: ["Entrepreneur", "Lawyer", "Consultant", "Journalist", "Creative director", "Product manager", "Political strategist"],
    strengths: ["Rapid lateral thinking under pressure", "Persuasion and debate", "Generating creative solutions to novel problems", "Spotting opportunities before anyone else", "Adapting on the fly when plans fall apart"],
    blindSpots: ["Starts many things, finishes few", "Argues for its own sake — can exhaust people", "Inconsistent follow-through on commitments", "Dismisses practical details as beneath them", "Can come across as combative or contrarian"],
    energyPattern: "Energized by variety, debate, and new ideas. Gets bored in repetitive or overly structured environments. Needs intellectual stimulation to stay present and engaged.",
    socialStyle: "Socially fluid and charismatic. Enjoys playing devil's advocate. Can connect with almost anyone but rarely goes deep unless intellectually challenged. Loves banter.",
    communicationTip: "Match their energy and push back on their ideas — they enjoy the sparring. Don't be offended if they argue against their own position. They respect intellectual confidence.",
    practiceScenarios: ["Going deeper in a conversation beyond surface banter", "Resolving a conflict with a close friend", "Following up on an unanswered message without seeming needy", "Listening without offering solutions — a friend needs to vent", "Saying no to a request without over-explaining"],
  },
  INFJ: {
    nickname: "The Advocate",
    tagline: "Rare visionaries who combine deep empathy with long-term strategic thinking.",
    careers: ["Counselor/therapist", "Writer", "Social worker", "Professor", "Nonprofit leader", "UX researcher", "Clergy or spiritual director"],
    strengths: ["Deep empathy and insight into what people really need", "Long-term vision guided by values", "Strong written and verbal communication", "Commitment to meaningful causes", "Ability to inspire others toward a shared purpose"],
    blindSpots: ["Burns out helping others at their own expense", "Avoids conflict even when it's necessary", "Can be overly idealistic about people and situations", "Takes criticism personally even when it's objective", "Withdraws when overwhelmed rather than communicating needs"],
    energyPattern: "Introverted despite strong people skills. Social interactions drain them faster than expected. Needs long recovery time after intense social events.",
    socialStyle: "Warm, attentive, and deeply perceptive one-on-one. Struggles in large groups. Builds deep connections slowly. Will disappear if a relationship stops feeling authentic.",
    communicationTip: "Connect on values and meaning before moving to logic. They read people instinctively — don't try to perform. Ask about their inner world and they'll open up fully.",
    practiceScenarios: ["Approaching a stranger at a coffee shop", "Networking at an industry conference", "Making small talk with the person next to you on a flight", "Telling a friend something difficult but necessary", "Starting a conversation at a party where you know nobody"],
  },
  INFP: {
    nickname: "The Mediator",
    tagline: "Idealistic, deeply empathetic, and guided by a strong internal value system.",
    careers: ["Writer/author", "Counselor", "Social worker", "Artist/designer", "Psychologist", "Teacher", "Nonprofit worker"],
    strengths: ["Deep emotional empathy and attunement", "Creative expression in multiple forms", "Strong personal values as a decision compass", "Genuine open-mindedness toward others", "Sees the potential and best in people"],
    blindSpots: ["Avoids conflict to a fault — allows resentment to build", "Gets lost in idealism and neglects practicality", "Overly self-critical after mistakes", "Easily overwhelmed by harsh or high-pressure environments", "Struggles with structure, deadlines, and admin"],
    energyPattern: "Highly introverted. Needs creative and emotional outlets to function. Large social settings drain quickly. Needs time alone to process feelings and recharge.",
    socialStyle: "Quiet in large groups but fully engaged one-on-one. Connects through shared values and emotional honesty. Deeply loyal to those they trust. Withdraws when feeling misunderstood.",
    communicationTip: "Approach with warmth and authenticity. Don't push — let them open at their own pace. Connect through feelings and shared values. Harsh directness shuts them down entirely.",
    practiceScenarios: ["Approaching someone you find attractive at a bar or event", "Asking someone out on a first date", "Speaking up with your idea in a team meeting", "Setting a boundary with someone who pushes back", "Saying no to a friend's invitation without damaging the friendship"],
  },
  ENFJ: {
    nickname: "The Protagonist",
    tagline: "Charismatic leaders who bring out the potential in everyone around them.",
    careers: ["Life coach/counselor", "Teacher/professor", "HR director", "Public speaker", "Nonprofit executive", "Sales leader", "Politician"],
    strengths: ["Reading and motivating people accurately", "Building genuine connections quickly", "Articulate and inspiring communication", "Long-term commitment to others' growth", "Natural leadership without domination"],
    blindSpots: ["Over-extends for others at their own expense", "Struggles to say no — chronic overcommitment", "Can be subtly manipulative without intending to be", "Takes others' problems personally", "Neglects their own needs until they burn out"],
    energyPattern: "Energized by meaningful human connection. Can socialize at length but needs quiet recovery time. Long periods of isolation drain their sense of purpose.",
    socialStyle: "Highly attuned to group dynamics. Focuses on others in conversation — asks questions, listens deeply. Makes people feel genuinely seen. Draws others naturally.",
    communicationTip: "Engage their heart and their vision together. Ask what they want for themselves, not just for others. Acknowledge their contributions directly — they often feel unseen despite giving everything.",
    practiceScenarios: ["Saying no to a request without over-explaining", "Confronting someone who crossed a line", "Setting a boundary with someone who pushes back", "Being honest with a friend about something that hurt you", "Receiving a compliment without deflecting it"],
  },
  ENFP: {
    nickname: "The Campaigner",
    tagline: "Enthusiastic, creative, and sees possibility and potential in everything and everyone.",
    careers: ["Entrepreneur", "Creative director", "Journalist", "Counselor", "Performer/actor", "Brand strategist", "Teacher"],
    strengths: ["Infectious enthusiasm and genuine energy", "Creative thinking and rapid ideation", "Reading emotional subtext in conversations", "Building connections quickly and naturally", "Adapting to new environments with ease"],
    blindSpots: ["Difficulty following through on ideas — leaves trails of unfinished projects", "Easily distracted by the next new thing", "Overcommits and underdelivers", "Struggles with routine, admin, and repetitive tasks", "Emotionally reactive under pressure"],
    energyPattern: "Gains energy from novelty, creativity, and human connection. Gets bored fast in repetitive environments. Needs alone time to process emotions despite appearing fully extraverted.",
    socialStyle: "Warm, expressive, and fully engaging. Connects through enthusiasm and storytelling. Can make anyone feel special. Tends to go wide rather than deep by default.",
    communicationTip: "Match their energy and let conversations be playful. Connect emotionally before going logical. Give them room to explore ideas without forcing an immediate conclusion.",
    practiceScenarios: ["Going deeper in a conversation beyond surface banter", "Being vulnerable with a friend about something personal", "Following up on an unanswered message without seeming needy", "Setting a boundary with a family member", "Reaching out to an old friend after a long gap"],
  },
  ISTJ: {
    nickname: "The Logistician",
    tagline: "Reliable, methodical, and takes every commitment seriously.",
    careers: ["Accountant/auditor", "Project manager", "Military officer", "Engineer", "Database administrator", "Financial analyst", "Law enforcement"],
    strengths: ["Exceptional reliability and follow-through", "Attention to detail — catches what others miss", "Systematic and procedural thinking", "Strong sense of duty and responsibility", "Excellent memory for facts, history, and procedures"],
    blindSpots: ["Resistant to change and new approaches", "Inflexible once a method or process is set", "Struggles to express emotions openly", "May prioritize rules over people's needs in edge cases", "Difficulty improvising when structure breaks down"],
    energyPattern: "Introverted and routine-oriented. Consistent social contact is manageable in small doses. Large, unpredictable social settings are draining. Needs structure and predictability.",
    socialStyle: "Reserved and somewhat formal at first. Warms up slowly through consistent, repeated interactions. Loyal and deeply dependable once trust is established.",
    communicationTip: "Be clear, specific, and always follow through on what you say. They trust actions over words completely. Don't push emotional expression — respect their reserved nature.",
    practiceScenarios: ["Starting a conversation at a party where you know nobody", "Networking at an industry conference", "Making small talk at a work social event", "First date conversation — keeping it natural", "Introducing yourself to a new neighbor"],
  },
  ISFJ: {
    nickname: "The Defender",
    tagline: "Warm, caring, and deeply committed to the people and traditions they value.",
    careers: ["Nurse/healthcare worker", "Teacher", "Social worker", "Administrative professional", "Counselor", "Librarian", "HR specialist"],
    strengths: ["Exceptional care and attentiveness to others", "Reliability and consistency under pressure", "Attention to detail in service of people", "Memory for personal details people share", "Warmth, hospitality, and genuine belonging-making"],
    blindSpots: ["Difficulty saying no — chronically overextends", "Avoids conflict even when it's genuinely needed", "Suppresses their own needs and resentment builds", "Overly modest about their own contributions", "Resistant to change even when beneficial"],
    energyPattern: "Introverted but people-focused. Energized by helping in familiar, structured settings. Large and unpredictable gatherings are draining. Needs consistency.",
    socialStyle: "Warm and attentive one-on-one. Remembers specific details about people they care for. Doesn't seek the spotlight. Shows love and care through action rather than words.",
    communicationTip: "Show genuine appreciation for what they do specifically. Ask how they are — they rarely volunteer it. Give them time to process before responding to large requests.",
    practiceScenarios: ["Initiating plans with someone you'd like to know better", "Telling a friend something difficult but necessary", "Setting a boundary with someone who pushes back", "Speaking up with your idea in a team meeting", "Asking for what you need without apologizing"],
  },
  ESTJ: {
    nickname: "The Executive",
    tagline: "Organized, direct, and a natural enforcer of order and results.",
    careers: ["Manager/executive", "Military officer", "Judge/lawyer", "Financial officer", "Operations manager", "School principal", "Police officer"],
    strengths: ["Getting things done efficiently and on time", "Leading through clear and consistent expectations", "Decisive under pressure", "Organizing people and processes toward a goal", "Upholding standards and holding others accountable"],
    blindSpots: ["Can be rigid and judgmental about alternative approaches", "Struggles to adapt when conventional methods fail", "Blunt in ways that can damage relationships", "Values tradition and status over fresh thinking", "May steamroll opposition rather than hearing it out"],
    energyPattern: "Energized by being productive and having clear authority. Social events with clear purpose are fine. Aimless socializing feels wasteful. Does not enjoy idle time.",
    socialStyle: "Confident and direct in social settings. Takes charge naturally and often immediately. Respects hierarchy and expects others to also. Prefers practical, results-oriented conversations.",
    communicationTip: "Be direct and concrete. Have your facts prepared. Don't challenge them emotionally — reframe disagreements around logic, outcomes, and results.",
    practiceScenarios: ["Listening without offering solutions — a friend needs to vent", "Having a difficult conversation without steamrolling", "Being vulnerable with a friend about something personal", "Recovering after saying something too blunt", "Receiving a compliment without deflecting it"],
  },
  ESFJ: {
    nickname: "The Consul",
    tagline: "Warm, social, and naturally brings people together in harmony.",
    careers: ["Teacher", "HR manager", "Event coordinator", "Sales representative", "Healthcare worker", "Public relations", "Social worker"],
    strengths: ["Building and maintaining social harmony", "Genuine warmth and care for others", "Organizational ability in service of people", "Sensitivity to group dynamics and mood", "Loyalty to people and community"],
    blindSpots: ["Seeks approval and is vulnerable to criticism", "Avoids difficult truths to keep the peace", "Sacrifices own needs for others' comfort", "Can be overly concerned with social standing", "Struggles with abstract or highly theoretical thinking"],
    energyPattern: "Energized by social connection and being needed. Isolation is genuinely draining and disorienting. Needs frequent positive feedback and affirmation from others.",
    socialStyle: "Warm, hospitable, and highly attentive. Remembers personal details. Creates belonging easily and quickly. Can be hurt deeply when social harmony breaks down.",
    communicationTip: "Lead with warmth and appreciation before anything else. They respond to emotional acknowledgment. Give feedback gently — they take criticism personally even when it's professional.",
    practiceScenarios: ["Saying no to a friend's invitation without damaging the friendship", "Disagreeing with a group when you're the only dissenting voice", "Being honest with a friend about something that hurt you", "Setting a boundary without over-apologizing", "Confronting someone who crossed a line"],
  },
  ISTP: {
    nickname: "The Virtuoso",
    tagline: "Cool-headed, practical, and exceptionally skilled with systems and physical tools.",
    careers: ["Engineer", "Mechanic/technician", "Pilot", "Forensic scientist", "Programmer", "Surgeon", "Entrepreneur"],
    strengths: ["Calm and analytical in a crisis", "Exceptional hands-on problem solving", "Practical and efficient thinking", "Independence and complete self-sufficiency", "Observational acuity in real-time situations"],
    blindSpots: ["Emotionally distant and genuinely hard to read", "Commitment-averse — resists being locked in", "Appears blunt or indifferent to others' feelings", "Impulsive in the short term despite long-term logic", "Difficulty expressing feelings even when they exist"],
    energyPattern: "Introverted and action-oriented. Recharges through solitary practical activity. Social interaction in large doses feels purposeless and exhausting.",
    socialStyle: "Quiet and observant. Opens up around shared activities rather than pure conversation. Not naturally expressive but deeply loyal in their actions.",
    communicationTip: "Skip the small talk — go straight to the practical point. Do things together rather than just talking. Respect their need for space. Don't push for emotional expression.",
    practiceScenarios: ["Starting a conversation at a party where you know nobody", "First date conversation — keeping it natural", "Asking someone out on a first date", "Initiating plans with someone you'd like to know better", "Reaching out to an old friend after a long gap"],
  },
  ISFP: {
    nickname: "The Adventurer",
    tagline: "Gentle, artistic, and deeply attuned to their senses and personal values.",
    careers: ["Artist/designer", "Musician", "Physical therapist", "Veterinarian", "Chef", "Photographer", "Fashion designer"],
    strengths: ["Strong aesthetic sensibility and attention to beauty", "Empathy and emotional attunement", "Living fully in the present moment", "Non-judgmental openness toward others", "Hands-on creativity and craftsmanship"],
    blindSpots: ["Avoids conflict and confrontation at all costs", "Overly sensitive to criticism — takes it deeply personally", "Hard to read — doesn't assert needs until overloaded", "Easily overwhelmed by harsh or high-pressure environments", "Can leave things unfinished when inspiration fades"],
    energyPattern: "Introverted and sensory-driven. Needs beauty, creativity, and calm to recharge. Social events that feel forced or inauthentic are deeply exhausting.",
    socialStyle: "Warm but reserved. Opens up gradually through shared experiences. Shows care through small thoughtful gestures. Detects fakeness quickly and withdraws from it.",
    communicationTip: "Create a calm and relaxed environment. Let them set the pace. Connect through shared sensory experiences — food, music, art, nature. They communicate more through action than words.",
    practiceScenarios: ["Approaching someone you find attractive at a bar or event", "Speaking up with your idea in a team meeting", "Saying no to a request without over-explaining", "Confronting someone who crossed a line", "Disagreeing with a colleague professionally"],
  },
  ESTP: {
    nickname: "The Entrepreneur",
    tagline: "Bold, perceptive, and thrives in fast-moving, high-stakes situations.",
    careers: ["Entrepreneur", "Sales executive", "Emergency responder", "Athlete/coach", "Trader", "Real estate agent", "Detective"],
    strengths: ["Reading people accurately in real time", "Acting decisively under pressure and uncertainty", "Practical problem solving on the fly", "Persuasion and negotiation", "High energy and rapid adaptability"],
    blindSpots: ["Impatient with theory or long-term abstract planning", "Risk-taking can become genuinely reckless", "Steamrolls others' feelings when moving fast", "Easily bored — may abandon projects mid-execution", "Struggles with abstract conceptual thinking"],
    energyPattern: "Highly energized by action and social interaction. Gets restless and frustrated without stimulation and variety. Needs new challenges to stay fully engaged.",
    socialStyle: "Bold, charismatic, and reads the room immediately. Thrives in larger social settings. Connects through humor, challenge, and shared experiences rather than conversation.",
    communicationTip: "Keep it fast-paced and practical. Skip the theory — ground everything in real-world action and tangible outcomes. Match their directness without hesitation.",
    practiceScenarios: ["Going deeper in a conversation beyond surface banter", "Listening without offering solutions — a friend needs to vent", "Resolving a conflict with a close friend", "Being vulnerable with a friend about something personal", "Following up on an unanswered message without seeming needy"],
  },
  ESFP: {
    nickname: "The Entertainer",
    tagline: "Spontaneous, energetic, and brings life and joy into every room they enter.",
    careers: ["Performer/actor", "Event planner", "Sales representative", "Early childhood teacher", "Tour guide", "Personal trainer", "Public relations"],
    strengths: ["Natural stage presence and infectious energy", "Connecting with people instantly and warmly", "Adaptability and improvisation under pressure", "Observing and responding to emotions in real time", "Creating fun, engagement, and a sense of belonging"],
    blindSpots: ["Easily distracted — struggles with sustained focus", "Avoids difficult emotions and hard conversations", "Impulsive with decisions — acts before thinking", "May prioritize fun over responsibility when it matters", "Needs external validation to feel secure"],
    energyPattern: "Highly social — gains energy from people and stimulation. Isolation and routine are deeply draining. Needs constant novelty, social engagement, and variety.",
    socialStyle: "The life of the room. Connects through humor, energy, and storytelling. Everyone feels noticed around them. Connections tend to stay at a surface level without deliberate effort to go deeper.",
    communicationTip: "Keep things light and fun to start — they open up when they feel safe and unjudged. Use humor as an entry point. Push gently to go deeper once rapport is built.",
    practiceScenarios: ["Having a difficult conversation you've been avoiding", "Setting a boundary with someone who pushes back", "Resolving a conflict with a close friend", "Being vulnerable with a friend about something personal", "Telling a friend something difficult but necessary"],
  },
};
